import "./main.scss";
import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import { Providers } from "../providers";
import { HtmlWithTheme } from "../components/HtmlWithTheme";
import { Navigation } from "@/components/navigation";
import { Footer } from "@/components/footer";

const mate = Noto_Sans({ subsets: ["latin"], weight: ["300", "400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <HtmlWithTheme>
        <body className={mate.className}>
          <div className="fluid-container page-wrapper">
            <Navigation
              menuItems={[
                { path: "/", label: "Home" },
                { path: "/about", label: "About" },
                { path: "/blog", label: "Blog" },
              ]}
            />
            {children}
          </div>

          <Footer />
        </body>
      </HtmlWithTheme>
    </Providers>
  );
}
